### ISSUE TITLE
util.py Depends on resource

### ISSUE THREAD

**Issue by definitelysean** [openvax/gtfparse#5]
util.py calculates the memory used by the current process using the **resource** module. This module is *nix specific, and can't be used on Windows. In favor of broader cross-platform compatibility, this module could use psutil to make the same calculation (see this [Stack Overflow](http://stackoverflow.com/questions/938733/total-memory-used-by-python-process) question for an example)

I encountered this issue in trying to use pyensembl (which depends on gtfparse) from a Windows 10 box.

**Comment by mattiyeh** [comment]
I just ran into the same issue with a tool that depends on _gtfparse_. On my windows box, I just edited _util.py_ to no longer import resource and made _memory_usage()_ return some constant number, and I was able to continue.

Please consider following the above suggestion to use something more cross-platform rather than the unix-specific _resource_ module.

**Comment by iskandr** [comment]
@mattiyeh & @definitelysean -- do either of you mind submitting a PR with how you'd prefer to get memory usage in a Windows compatible way?

**Comment by iskandr** [comment]
Came up as a problem for another Windows user: https://github.com/openvax/varcode/issues/234
